name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
  
jobs:
  deploy-to-github-pages:
    # use ubuntu latest version
    runs-on: ubuntu-latest
    steps:
    
    #uses GitHubs checkout action
    - uses: actions/checkout@v2
    
    #set up .NET core sdk
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
        
    #publishes blazor project to release
    - name: Publish .NET core project
      run: dotnet publish portfolio.csproj -c Release -o release --nologo
      
    - name: Commit wwwroot to pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
